name: TuringKi
description: Personal Blog
url: http://turingki.github.com
pygments: true
permalink: /:categories/:year-:month-:day-:title/
relative_permalinks: false
markdown: kramdown
#markdown: rdiscount
#markdown: redcarpet
baseurl: 
